name: Check redirections
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install EMMOntoPy
      run: |
        pip install --upgrade pip
        pip install EMMOntoPy

    - name: Check redirections
      run: |
        redirectioncheck .github/expected_redirections.yaml
